### PR TITLE
Overlay Waterways

### PR DESCRIPTION
**Pull request by fosskers**
This will increase friction to infinity for any pixel where a waterway is detected.

### CODE REVIEW

**Comment by fosskers** [comment]
2017-12-01-132149_1918x1078_scrot

**Comment by fosskers** [comment]
San Fran:
2017-12-01-132329_1918x1078_scrot

**Comment by fosskers** [comment]
Fresno:
2017-12-01-132919_1918x1078_scrot

**Comment by fosskers** [comment]
Is it just me, or are roads *increasing* friction here? Purple is supposed to be in the direction of "more friction", but this here seems to be telling us that it's must faster just to walk across the empty fields 😆

**Comment by fosskers** [comment]
Nice shot of waterways maxing-out friction:
2017-12-01-141440_1918x1078_scrot

**Comment by fosskers** [comment]
Hm, no, the purple roads might be a quirk of how colouring works... I'll think more about that.

**Comment by fosskers** [comment]
Woops, crap, these results are wrong. They're not including any of the `Polygons`. The [fused](https://github.com/geotrellis/geotrellis-friction-surface/pull/5/files#diff-be7459d474c126ebfad4ac97b78fa97aR155) value is never being called.

**Comment by fosskers** [comment]
The `ocean` colorramp is perfect:

2017-12-04-083240_1918x1078_scrot

**Comment by fosskers** [comment]
A lake, I think. Whatcha doin' there Rasterizer...

2017-12-04-083524_1918x1078_scrot

**Comment by fosskers** [comment]
Otherwise, there isn't really much of a visible difference having added the Polygons.

**Comment by fosskers** [comment]
False alarm! It's a water treatment plant:

2017-12-04-085150_1918x1078_scrot

**Review by echeipesh — APPROVED** [review]

**Review by jamesmcclain — APPROVED** [review]

**Pull request merged**
